### ISSUE TITLE
Updating redactor.js

### ISSUE THREAD

**Issue by aaadotpm** [mazelife/django-redactor#15]
Has anyone tried updating to newer versions of redactor.js successfully? 
Redactor.js is currently in Version 9.0.4.

**Comment by defbyte** [comment]
I too would love to see this, and am considering forking this and giving it a shot - however, I have no idea how many changes have been made to Redactor in the last two major version numbers.

**Comment by mazelife** [comment]
Updated 9.1.9

**Comment by aaadotpm** [comment]
Great stuff! Thanks!
