### ISSUE TITLE
Installing from PyPi does not work. Throws "cannot import name RedactorEditor" error.

### ISSUE THREAD

**Issue by gauravtoshniwal1989** [mazelife/django-redactor#16]
Gives error:

``` python
cannot import name RedactorEditor
```

However, it installs without any issues directly from GitHub

``` shell
pip install -e git+https://github.com/mazelife/django-redactor.git#egg=redactor
```

**Comment by defbyte** [comment]
I'm just answering this as a user of this package, not as a creator:
I believe this is due to the fact that there is another project with the same name that is on PyPi, see issue #5

**Comment by mazelife** [comment]
That's correct; the django-redactor package on PyPI (https://pypi.python.org/pypi/django-redactor/0.2) is not this one.
