### ISSUE TITLE
loading image with a Russian names

### ISSUE THREAD

**Issue by igorakintev** [mazelife/django-redactor#20]
If image name contains russian chars (тест.jpg) we get error UnicodeEncodeError at /redactor/upload/image/ 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

**Comment by mazelife** [comment]
Is this still an issue? I see you closed it, but if it's a problem, I'd be happy to look into it.

**Comment by igorakintev** [comment]
Sorry. I confused you with django-wysiwyg-redactor. Your code can not be this error.
