### ISSUE TITLE
Translations are not working

### ISSUE THREAD

**Issue by apalazon** [mazelife/django-redactor#21]
Dear all,

I have problems using the spanish translation. Redactor stops working when I set other language.

I have detected that the translation files included in  redactor / static / django-redactor / redactor / langs are obsolete, as I think that they are from an older redactor version.

I have tried using some of the files from the curent version. You can find those there:
http://imperavi.com/redactor/docs/languages/

When you replace the translations with these files, it works ok.

Regards,

**Comment by philippeowagner** [comment]
Had issues with the languages as well...

**Comment by mazelife** [comment]
Just pushed a fix for this.
