### ISSUE TITLE
Admin documentation

### ISSUE THREAD

**Issue by dmeehan** [mazelife/django-redactor#3]
I could not get the admin functionality to work with the current documentation:

class MyAdmin(admin.ModelAdmin):
    formfield_overrides = {
            'widget': AdminRedactorEditor()
        }
    }

However, this did work:

from django.db import models
from django.contrib import admin

from redactor.widgets import AdminRedactorEditor

from myapp.models import MyModel

class MyModelAdmin(admin.ModelAdmin):
    formfield_overrides = {
           models.TextField:{'widget': AdminRedactorEditor},
        }

admin.site.register(MyModel, MyModelAdmin)

Perhaps more explicit documentation would be helpful. 

Thanks.

**Comment by mazelife** [comment]
Thanks for the notice. My code in that example is, indeed, not correct. I updated the README with the correct useage of `formfield_overrides`.
