### ISSUE TITLE
how to modify lang setting ?

### ISSUE THREAD

**Issue by maximefavier** [mazelife/django-redactor#4]
Hi, 

First thank for this great plugin, i really liked it.
Now i would like to set the lang to 'fr' but in order to do that i must include the language file but i can't do that in the django back-office ... How can i do it ? Maybe your widget need a new argument with the path of this language file...

Thank in advance for your response.

**Comment by maximefavier** [comment]
Ok it's easy. I changed the widget.py and i included the fr.js like this : 

#(ligne 101)
def media(self):
        js = (
            'django-redactor/lib/jquery-1.7.min.js',
            'django-redactor/redactor/redactor.js',
            'django-redactor/redactor/setup.js',
            'django-redactor/redactor/langs/fr.js',
        )
        css = {
            'screen': [
                'django-redactor/redactor/css/redactor.css',
            ]
        }

**Comment by mazelife** [comment]
You don't have to modify the source code to load the javascript. You can just add a Media class to your form. See the example from the README that I added.
