### ISSUE TITLE
Submit to PyPI

### ISSUE THREAD

**Issue by yprez** [mazelife/django-redactor#5]
It would be great if this package would be listed in PyPI, and installable with pip.

The `setup.py` is already there.
The only problem I see with this is that the name is already taken: http://pypi.python.org/pypi/django-redactor/ :(

**Comment by mazelife** [comment]
The issue with the name having been taken is kind of a big one. I don't want to create confusion that this package is somehow related to the `django-redactor package` already on PyPI by naming it something like django-redactor2. I also don't want to have to rename this whole project if I can avoid it. That said, this app is totally pip-installable:

```
    pip install https://github.com/mazelife/django-redactor/tarball/v1.2.1
```

That would install the latest version of this package. But I understand how listing it with PyPI would be preferable. I'll have to think about this one.

**Comment by roberts81** [comment]
Sharing the same name as another package even if not on PyPi has some serious disadvantages and is likely to create confusion for anyone trying to use one or the other.  Its probably worth brainstorming a new name.

**Comment by cliffton** [comment]
Yeah if this was available on PyPi is would be great ! I just spent an hour trying to figure out whats wrong ! Then I replaced the redactor directory in the site-packages folder with the zip from github and it worked :(

**Comment by philippeowagner** [comment]
For me personally, a package not listet to PyPI is not a package to use in production. Probably it's too late to remodel/rename the complete repository due to previous usage with `pip install -e ...` by others. @mazelife why not fork this app to something like `django-redactoreditor` and get it listed to PyPI and keep this as legacy app?

**Comment by mazelife** [comment]
forked and renamed: https://github.com/mazelife/django-redactoreditor

The "django-redactoreditor" package is now listed on PyPI.

**Comment by defbyte** [comment]
I guess now would be a good time to update any project that requires this package ;)

Will this repository remain for a time, for procrastinators like myself? (and the fact I don't want to rock the boat on certain projects)
