### ISSUE TITLE
License

### ISSUE THREAD

**Issue by roberts81** [mazelife/django-redactor#6]
Looks like a fantastic project.  However, you indicate that django-redactor is licensed under CC-Attribution/NonCommercial. You note that this is because the underlying Redactor platform is licensed under the same license.  So, on one hand, that was the right move, since you can't unrestrict the included code.  On the other hand, redactor also licenses their code under a separate, developer license for commercial and open-source uses; but, without an explicit waiver from you, we're stuck with the CC non-commercial license on any usages of your project even if we purchase an unrestricted (or less restricted) license from Redactor.js.  

I wonder if you would consider alternative licensing language that incorporate the noncommercial license out of the box, but which would make your software available for commercial or less-restricted open-source projects, if the user has a proper redactor license.  I thought I'd check first before I spent brain cells on any specific suggestions of how that could be achieved, although they would be quite simple.

 (Or maybe you think the web should only be used for non-commercial purposes, in which case, that's your right, and you've chosen a great license for that! :) ) 

Sources: I'm a reformed IP attorney, turned web-hacker. :)

**Comment by roberts81** [comment]
PS, one avenue to a less restrictive license would be for you (or whoever the copyright owner of the code in this repository is) to have purchased a developer license from redactorjs.  From http://redactorjs.com/download/: 

> **Can I use Redactor in my project, which is published under GPL, MIT, BSD, or other open-source/copyleft license?**
> Yes, go ahead! You just need to purchase the Developer License. No additional fees will be applied and there are 
> no special terms or conditions, until Redactor is properly "linked" in your software.

Don't get me wrong, I'm not pushing you to buy a license, just checking whether you might have already done so, in which case you could just release your project under an MIT or BSD license, consistently with most django-based packages. If not, I could help out with some language to add to your license which would let users of the package carry the burden of purchasing the Redactor  license.

**Comment by mazelife** [comment]
Thanks for your interest. If you look at my other open source projects, you'll see I definitely prefer a less-restrictive license like BSD or Apache. I believe I missed the part about them providing a separate license for developers (or perhaps they updated the site recently to clarify the point). I've purchased a personal license, but I'm not at all opposed to buying a developer license. I like to support open source development when I can, and finding a well-designed, lean but capable WYSIWYG after years of looking is well worth $99. I'll look into doing that at which point I'm happy to change the license. That said, I wonder if writing the license in such a way as to let users of the package carry the burden of purchasing the Redactor license would actually send more money their way in the long run?

**Comment by roberts81** [comment]
Their license http://redactorjs.com/license/ is all sorts of ambiguous, even in light of their "FAQ" answers (e.g.,  what is "No additional fees will be applied and there are no special terms or conditions, _until Redactor is properly "linked" in your software._" supposed to mean?).  So a user may want to consider purchasing their own Redactor license before using it in a commercial application even if they had adopted an open-source project from a source who had purchased a developer license, just to be safe. 

Anyhow, I think you could go either way: get the developer license and license this as BSD or Apache, and let commercial users figure out for themselves whether they think they need to or _should_ purchase a license from Imperavi, or you could add something like the following sentence to your License.txt & readme if you wanted to just waive the non-commercial clause for legitimate Redadctor purchasers (this type of waiver is explicitly permitted by the CC license)

> "The noncommercial restrictions of the license (e.g., Section 4(b)) are waived for any user who purchases a 
> legitimate commercial license to the redactor.js library."

This would essentially convert the CC license to an "attribution-only" license, similar to BSD, but just for those users who purchase the Imperavi license.  Open source users would still be under the noncommercial clause (by necessity, unless you purchase the developer license), but legitimate imperavi license holders could then feel safe to move forward with their endeavors.

**Comment by mazelife** [comment]
I'll likely end up purchasing a dev license here soon, but in the mean time I've added the language you suggest to the license and README (commits a52c6b2b7d and 4eb50c95a4). This way any users who wish to use this project in a commercial context need only purchase a license.

**Comment by roberts81** [comment]
Cool. That works!
