### ISSUE TITLE
Installation updates

### ISSUE THREAD

**Issue by fission6** [mazelife/django-redactor#7]
Would be good to make a note about including the needed javascript and css files somewhere in a specific template or base template. 

For the admin widget this is taken care of.

nice plugin none the less.

**Comment by mazelife** [comment]
The standard `RedactorEditor` includes a media definition, same as the admin one. In your template code you just have to remember to include `{{ form.media }}` somewhere. This section of the Django docs details that: https://docs.djangoproject.com/en/1.4/topics/forms/media/#media-on-forms

**Comment by fission6** [comment]
right, all i was saying is it maybe a good idea to add what you've typed above to the README - thats all.

**Comment by mazelife** [comment]
Gotcha. That seems like a good idea and I've added it to the README.

**Comment by fission6** [comment]
good stuff man!
