### ISSUE TITLE
custom css

### ISSUE THREAD

**Issue by ouhouhsami** [mazelife/django-redactor#9]
Hi, 

I use your app, but I got a problem setting custom css. In fact, due to the way redactor.min.js work, it adds :   + this.opts.path + '/css/' before the this.opts.css  at this point : https://github.com/mazelife/django-redactor/blob/master/redactor/static/django-redactor/redactor/redactor.js#L816
so that, I think (because I tried and didn't succeed) that this feature is kind of broken.

If I remove  + this.opts.path + '/css/'  from this line, it works fine. From there, all the code here https://github.com/mazelife/django-redactor/blob/master/redactor/widgets.py#L91 is more or less broken: it would work if redactor.js doesn't add it own prefix to css. 
Don't know if there is a good way to work around this path problem.

Regards,

**Comment by mazelife** [comment]
The only solution I can see is to modify the original redactor.js file to use the full path specified when the widget is rendered. Given that being able to apply CSS to the contents of the editor is a pretty significant need and that the change itself is quite small (00a3a7d), I've gone ahead and done that. I also re-minified the source, so you can continue to use redactor.min.js.

**Comment by ddurst** [comment]
It seems that the fullscreen toggle, when used to go from full back down to mini, removes the newly-added contents. Is this related to this app, or redactor itself?
